---
name: pre-commit
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: pre-commit
        run: |
          sudo apt install -y pre-commit git
          pre-commit run --all-files
